#!/bin/bash
# taco client

connect_db () {
    if [[ -z "${MARIADB_SERVICE_HOST}" ]]; then
        echo "Error) No MARIADB_SERVICE_HOST exists."
        echo "Are you running TACOS as a docker container?"
        echo "You can connect to DB only when running TACOS in kubernetes."
    else
        mysql -h mariadb -u root -p 
    fi
}
execute_taco () {
    openstack "$@"
}
run_taco () {
    # check if client can reach each openstack service.
    declare -A clients
    clients=(
        ["cinder"]="300"
        ["glance"]="300"
        ["keystone"]="300"
        ["neutron"]="200"
        ["nova"]="200"
    )
    
    while true; do
        for c in ${!clients[@]}; do
            code=$(curl --silent --output /dev/null --include \
                    --max-time 3 --write-out "%{http_code}" \
                    http://$c.openstack.svc.cluster.local:8080/)
            if [ x"$code" != x"${clients[$c]}" ]; then
                echo "$c service has a problem."
            fi
        done
        sleep 30
    done
}
test_taco () {
    # Get cirros image first if not found.
    #v=$(curl -s http://download.cirros-cloud.net/version/released)
    #if [ ! -f /usr/local/bin/cirros-${v}-x86_64-disk.img ]; then
    #    curl -sLo /usr/local/bin/cirros-${v}-x86_64-disk.img \
    #        http://download.cirros-cloud.net/${v}/cirros-${v}-x86_64-disk.img
    #fi
    # Run taco-test.sh
    /usr/local/bin/taco-test.sh
}
version_taco () {
    declare -a clients
    clients=("cinder" "glance" "neutron" "nova" "masakari" "openstack")
    header="%-10s\t%-10s"
    printf "$header\n" "Client" "Version"
    printf "=%.0s" {1..30}
    echo
    for c in ${clients[@]}; do
        [ x"$c" != x"masakari" ] && ver="--version" || ver="--masakari-api-version"
            
        printf "$header\n" "$c" "$($c $ver 2>/dev/null)"
    done
}
USAGE () {
    echo "USAGE: $0 {-h|-d|-e|-r|-t|-v}" 1>&2
    echo ""
    echo " -h --help            Display this help message."
    echo " -d --database        Connect to openstack database."
    echo " -e --execute         Execute taco command."
    echo " -r --run             Run taco client."
    echo " -t --test            Run taco-test.sh script."
    echo " -v --version         Show openstack client versions."
}
if [ $# -lt 1 ]; then
    USAGE
    exit 0
fi

OPT=$1
shift
# Get argument
while true
do
    case "$OPT" in
        -d | --database)
            connect_db
            break
            ;;
        -e | --execute)
            execute_taco "$@"
            break
            ;;
        -h | --help)
            USAGE
            break
            ;;
        -r | --run)
            run_taco
            break
            ;;
        -t | --test)
            test_taco
            break
            ;;
        -v | --version)
            version_taco
            break
            ;;
        *)
            echo Error: unknown option: "$OPT" 1>&2
            echo " "
            USAGE
            break
            ;;
    esac
done
